FROM ubuntu

MAINTAINER zlucan <zlucan@student.21-school.ru>

RUN apt-get update && apt-get upgrade -y && apt-get install -y default-jdk default-jre git vim emacs

# How to build it?
# docker build -t a04 .

# How to run it?
# docker run --rm -ti a04